import type { InsertCmsDownload } from "./cms-schema";

/** Seed data for the downloads page — file paths point to client/public/downloads */
export const defaultDownloadDocuments: InsertCmsDownload[] = [
  {
    title: "All in one claim form Occidental",
    description: "Occidental Insurance Company Ltd",
    category: "Form",
    fileSize: "163 KB",
    filePath: "/downloads/All in one claim form Occidental (1).pdf",
    icon: "building",
    published: true,
    sortOrder: 1,
  },
  {
    title: "All-Risks-Proposal",
    description: "Mayfair Insurance Company Limited",
    category: "Insurance",
    fileSize: "273 KB",
    filePath: "/downloads/All-Risks-Proposal.pdf",
    icon: "car",
    published: true,
    sortOrder: 2,
  },
  {
    title: "BURGLARY-BUSINESS-PREMISES-PROPOSAL-FORM",
    description: "Burglary business premises proposal form",
    category: "Form",
    fileSize: "441 KB",
    filePath: "/downloads/BURGLARY-BUSINESS-PREMISES-PROPOSAL-FORM GApdf.pdf",
    icon: "shield",
    published: true,
    sortOrder: 3,
  },
  {
    title: "Burglary-Edited-Fillable-Form",
    description: "Burglary edited fillable form",
    category: "Form",
    fileSize: "151 KB",
    filePath: "/downloads/Burglary-Edited-Fillable-Form.pdf",
    icon: "shield",
    published: true,
    sortOrder: 4,
  },
  {
    title: "CIC Personal Accident Proposal Form",
    description: "CIC personal accident brochure and proposal",
    category: "Brochure",
    fileSize: "431 KB",
    filePath: "/downloads/CIC-Personal-Accident-Brochure-Proposal-Form_V.102022 (1).pdf",
    icon: "heart",
    published: true,
    sortOrder: 5,
  },
  {
    title: "Claim Form English",
    description: "Standard English claim form",
    category: "Form",
    fileSize: "1.5 MB",
    filePath: "/downloads/CLAIM FORM ENGLISH_V4.pdf",
    icon: "file-text",
    published: true,
    sortOrder: 6,
  },
  {
    title: "Claim Form Property GA Damage or Loss",
    description: "Property damage or loss claim form",
    category: "Form",
    fileSize: "50 KB",
    filePath: "/downloads/CLAIM FORM_PROPERTY  GA DAMAGE OR LOSS.pdf",
    icon: "briefcase",
    published: true,
    sortOrder: 7,
  },
  {
    title: "Contractors-All-Risks",
    description: "Contractors all risks proposal form",
    category: "Form",
    fileSize: "303 KB",
    filePath: "/downloads/Contractors-All-Risks.pdf",
    icon: "building",
    published: true,
    sortOrder: 8,
  },
  {
    title: "Domestic-Package",
    description: "Domestic package proposal form",
    category: "Form",
    fileSize: "333 KB",
    filePath: "/downloads/Domestic-Package.pdf",
    icon: "heart",
    published: true,
    sortOrder: 9,
  },
  {
    title: "Domestic Package Proposal Form GA",
    description: "GA domestic package proposal form",
    category: "Form",
    fileSize: "428 KB",
    filePath: "/downloads/DOMESTIC-PACKAGE-PROPOSAL-FORM GA pdf.pdf",
    icon: "heart",
    published: true,
    sortOrder: 10,
  },
  {
    title: "Erection-All-Risks",
    description: "Erection all risks proposal form",
    category: "Form",
    fileSize: "307 KB",
    filePath: "/downloads/Erection-All-Risks.pdf",
    icon: "building",
    published: true,
    sortOrder: 11,
  },
  {
    title: "Fidelity-Guarantee",
    description: "Fidelity guarantee proposal form",
    category: "Form",
    fileSize: "279 KB",
    filePath: "/downloads/Fidelity-Guarantee.pdf",
    icon: "shield",
    published: true,
    sortOrder: 12,
  },
  {
    title: "Fire",
    description: "Fire insurance proposal form",
    category: "Form",
    fileSize: "307 KB",
    filePath: "/downloads/Fire.pdf",
    icon: "shield",
    published: true,
    sortOrder: 13,
  },
  {
    title: "Industrial All Risks Insurance Proposal Form",
    description: "Industrial all risks proposal form",
    category: "Form",
    fileSize: "228 KB",
    filePath: "/downloads/INDUSTRIAL ALL RISKS INSURANCE PROPOSAL FORM.pdf",
    icon: "building",
    published: true,
    sortOrder: 14,
  },
  {
    title: "Marine Cargo Proposal Form Mayfair",
    description: "Mayfair marine cargo proposal form",
    category: "Form",
    fileSize: "25 KB",
    filePath: "/downloads/Marine Cargo - Proposal Form Mayfair.pdf",
    icon: "globe",
    published: true,
    sortOrder: 15,
  },
  {
    title: "Mayfair Insurance New Motor Claim Form",
    description: "Mayfair motor claim form",
    category: "Form",
    fileSize: "169 KB",
    filePath: "/downloads/Mayfair Insurance New Motor Claim Form.pdf",
    icon: "car",
    published: true,
    sortOrder: 16,
  },
  {
    title: "Mayfair New Windscreen Claim Form",
    description: "Mayfair windscreen claim form",
    category: "Form",
    fileSize: "625 KB",
    filePath: "/downloads/Mayfair -New Windscreen Claim Form.pdf",
    icon: "car",
    published: true,
    sortOrder: 17,
  },
  {
    title: "Money Insurance Proposal Form",
    description: "Money insurance proposal form",
    category: "Form",
    fileSize: "284 KB",
    filePath: "/downloads/MONEY INSURANCE PROPOSAL FORM.pdf",
    icon: "briefcase",
    published: true,
    sortOrder: 18,
  },
  {
    title: "Motor Accident Claim Form GA",
    description: "GA motor accident claim form",
    category: "Form",
    fileSize: "132 KB",
    filePath: "/downloads/MOTOR ACCIDENT CLAIM FORM - NEW GA.pdf",
    icon: "car",
    published: true,
    sortOrder: 19,
  },
  {
    title: "Motor Claim Form OCCIDENTAL",
    description: "Occidental motor claim form",
    category: "Form",
    fileSize: "181 KB",
    filePath: "/downloads/Motor Claim Form OCCIDENTAL (3).pdf",
    icon: "car",
    published: true,
    sortOrder: 20,
  },
  {
    title: "Motor-Commercial",
    description: "Commercial motor proposal form",
    category: "Form",
    fileSize: "181 KB",
    filePath: "/downloads/Motor-Commercial.pdf",
    icon: "car",
    published: true,
    sortOrder: 21,
  },
  {
    title: "Motor-Private proposal form Mayfair",
    description: "Mayfair private motor proposal form",
    category: "Form",
    fileSize: "362 KB",
    filePath: "/downloads/Motor-Private proposal form Mayfair .pdf",
    icon: "car",
    published: true,
    sortOrder: 22,
  },
  {
    title: "Motor-Private",
    description: "Private motor proposal form",
    category: "Form",
    fileSize: "362 KB",
    filePath: "/downloads/Motor-Private.pdf",
    icon: "car",
    published: true,
    sortOrder: 23,
  },
  {
    title: "New Motor Claim OCC Form",
    description: "Occidental new motor claim form",
    category: "Form",
    fileSize: "162 KB",
    filePath: "/downloads/NEW MOTOR CLAIM OCC FORM (A4).pdf",
    icon: "car",
    published: true,
    sortOrder: 24,
  },
  {
    title: "PI Proposal Form",
    description: "Professional indemnity proposal form",
    category: "Form",
    fileSize: "60 KB",
    filePath: "/downloads/PI PROPOSAL FORM.pdf",
    icon: "briefcase",
    published: true,
    sortOrder: 25,
  },
  {
    title: "Political Violence Insurance Proposal Form",
    description: "Political violence insurance proposal",
    category: "Form",
    fileSize: "60 KB",
    filePath: "/downloads/POLITICAL-VIOLENCE-INSURANCE-PROPOSAL-FORM..pdf",
    icon: "shield",
    published: true,
    sortOrder: 26,
  },
  {
    title: "Public-Liability",
    description: "Public liability proposal form",
    category: "Form",
    fileSize: "272 KB",
    filePath: "/downloads/Public-Liability.pdf",
    icon: "briefcase",
    published: true,
    sortOrder: 27,
  },
  {
    title: "Tausi Motor Vehicle Claim Form",
    description: "Tausi motor vehicle claim form",
    category: "Form",
    fileSize: "244 KB",
    filePath: "/downloads/TAUSI MOTOR VEHICLE CLAIM FORM.pdf",
    icon: "car",
    published: true,
    sortOrder: 28,
  },
  {
    title: "Tausi Windscreen Window Claim Form",
    description: "Tausi windscreen claim form",
    category: "Form",
    fileSize: "244 KB",
    filePath: "/downloads/TAUSI WINDSCREEN  WINDOW CLAIM FORM.pdf",
    icon: "car",
    published: true,
    sortOrder: 29,
  },
  {
    title: "Travel Claim Form",
    description: "Travel insurance claim form",
    category: "Form",
    fileSize: "244 KB",
    filePath: "/downloads/TRAVEL _CLAIM FORM.pdf",
    icon: "globe",
    published: true,
    sortOrder: 30,
  },
  {
    title: "Windscreen Claim Form GA",
    description: "GA windscreen claim form",
    category: "Form",
    fileSize: "244 KB",
    filePath: "/downloads/Windscreen Claim Form GA.pdf",
    icon: "car",
    published: true,
    sortOrder: 31,
  },
];
